deployment = "deployment.toml"

[[contracts]]
name = "universal_groth16_verifier"
template_type = "Rust"

[[contracts]]
name = "universal_marlin_verifier"
template_type = "Rust"

[[contracts]]
name = "mini_bulletproofs_verifier"
template_type = "Rust"

[[contracts]]
name = "mini_clinkv2_verifier"
template_type = "Rust"
