[package]
name = "zkp"
version = "0.1.0"
authors = ["sun"]
edition = "2018"

[workspace]
members = [
    "math",
    "curve",
    "scheme"
]

[features]
default = ["parallel"]
std = ["math/std", "curve/std", "scheme/std"]
parallel = ["std", "math/parallel", "curve/parallel", "scheme/parallel"]

[dependencies]
math = { path = "math", default-features = false }
scheme = { path = "scheme", default-features = false }
curve = { path = "curve", default-features = false, features = [ "bls12_381", "bn_256"] }

[dev-dependencies]
rand = { version = "0.7" }
