[package]
name = "zkp"
version = "0.1.0"
authors = ["sun"]
edition = "2018"

[workspace]
members = [
    "math",
    "curve",
    "scheme"
]

[dependencies]
math = { path = "math" }
curve = { path = "curve" }
scheme = { path = "scheme" }
