[package]
name = "scheme"
version = "0.1.0"
authors = ["Sun <huachuang20@gmail.com>"]
edition = "2018"
description = "implementation of the different zero-knowledge proof system schemes"
keywords = ["zero knowledge", "cryptography", "zkSNARK", "SNARK", "Groth"]
categories = ["cryptography"]
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
math = { path = "../math", default-features = false, features = [ "derive" ] }
rand = { version = "0.7", default-features = false }
rayon = { version = "1", optional = true }
smallvec = "1.1.0"

[dev-dependencies]
csv = { version = "1" }
curve = { path = "../curve", default-features = false, features = [ "bls12_381", "bn_256" ] }

[features]
default = ["parallel"]
std = ["math/std"]
parallel = ["std", "math/parallel", "rayon"]
#print-trace = [ "bench-utils/print-trace" ]
