[package]
name = "universal_spartan_snark_verifier"
version = "0.1.0"
edition = "2018"

[dependencies]
ckb-std = "0.7.2"
postcard = { version = "0.5", default-features = false, features = ["alloc"] }

[dependencies.zkp-toolkit]
git = "https://github.com/sec-bit/ckb-zkp/zkp-toolkit"
default-features = false
features = ["spartan", "bn_256"]